### ISSUE TITLE
Document how to backup and restore your application directory

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno-docs#16]
This issue requests documenting how to backup and restore your application directory, as it's a frequently asked question.

**Comment by boldsuck** [comment]
https://github.com/boldsuck/haveno-reto-docs/blob/main/docs/backup_and_restoration.md
I would like to integrate the mkdocs workflow and then let's see what we can merge.

**Comment by boldsuck** [comment]
Can b closed, fixed by:
https://github.com/haveno-dex/haveno-docs/commit/c8571343c49f65dbbf34211d23b32c95387d3715
