### ISSUE TITLE
SEPA und SEPA instant

### ISSUE THREAD

**Issue by boldsuck** [haveno-dex/haveno-docs#6]
Hi,
You could add a note for SEPA & -Instant payments. That was new to me & at first I thought the boy was trying to fool me:
Traders from Switzerland and, for example, Great Britain also need City and Street for a SEPA transfer.

Banks outside the European Economic Area require the address of the payee to be provided in payment transactions.

The trader from Switzerland told me that the address only has to be approximately correct.
I gave him the city of my bank and a valid street address in that city. The money has arrived at me, but I can't vouch for that.

I can also do a PR if you want.

**Comment by woodser** [comment]
> I can also do a PR if you want.

That would be great.

Sounds like we just need to add a free form field to input an address, at least city and street?

**Comment by boldsuck** [comment]
I meant that as a note in the documentation.

I wouldn't change that in the Haveno client. Within Europe, the IBAN is sufficient. The name and BIC are optional. Haveno/bisq uses the name because of fraud risk. It's very rare that someone needs an address and street for SEPA. And you have to clarify in the chat beforehand whether the real or a fake address is OK. With or without a house number.

In my case it was a Turk with a EUR bank account in Switzerland to trade in the EU.

**Comment by woodser** [comment]
> I meant that as a note in the documentation.

Ah yes we're in the docs repo here. :)

Yeah any PRs to help with this documentation would be great. Thanks.

**Comment by boldsuck** [comment]
Added Note to SEPA
https://github.com/boldsuck/haveno-docs/commit/43464111e280f656a06707216d8067e855794f27
https://github.com/haveno-dex/haveno-docs/pull/21
