### ISSUE TITLE
Register new payment methods in the documentation

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno-docs#7]
Currently these [payment methods](https://github.com/haveno-dex/haveno-docs/tree/master/docs/the-project/payment-methods) are documented by @nihilist001 but not registered in [mkdocs.yml](https://github.com/haveno-dex/haveno-docs/blob/master/mkdocs.yml) to be published with the docs.

**Comment by boldsuck** [comment]
I'm learning mkdocs. Should the **Payment Methods** menu [look like this](https://boldsuck.github.io/haveno-docs/)?
Should we add all payments from @XMRZombi?

**Comment by woodser** [comment]
Yeah, we should add all payment methods.

**Comment by woodser** [comment]
The payment methods have been merged to master.

**Comment by boldsuck** [comment]
Side Menue works: https://boldsuck.github.io/haveno-docs/the-project/assets/#payment-methods-and-fiat-currencies
Links maeh: https://boldsuck.github.io/haveno-docs/the-project/payment_methods/F2F.md
All Payments: https://boldsuck.github.io/haveno-docs/the-project/payment-methods/A_all-methods/
Markup in all files still needs to be revised.

**Comment by boldsuck** [comment]
I think we can close this. Some are still missing eg: Moneygram
https://boldsuck.github.io/haveno-docs/the-project/payment_methods/0-all-methods/

Some help: https://en.bitcoin.it/wiki/Payment_methods
